### PR TITLE
Add some responive

### PR DESCRIPTION
**Pull request by schirrel**
The docs nav wasn't responsive i've add some :D

### CODE REVIEW

**Comment by remear** [comment]
This is failing with `Error: The jekyll-theme-minimal theme could not be found.`. Could you share your reason for wanting to set `theme`.

**Comment by schirrel** [comment]
@remear was a mistake, i've add that  to can see at gh, i will remove that

**Comment by thebenrob** [comment]
I'm having trouble testing locally at the moment, but I'm in favor of having responsive menus...I've occasionally tried to look up a link to share while on my phone and had problems.

**Comment by thebenrob** [comment]
@schirrel, thanks for the PR.  Sorry it took so long to review.  We had another PR (#67) that added similar functionality from a developer that has already signed the Adobe CLA.  In the interest of moving forward and getting responsiveness in the nav, I've just merged that one and will close this one.

**Pull request closed without merging**
