### PR TITLE
rework library relationships

### PR DESCRIPTION
**Pull request by spencerroan**
#### Purpose
convert library.resources into explicit relationships
reorganize the navigation a bit to bring sanity to the force.

### CODE REVIEW

**Review by remear — APPROVED** [review]
This looks good to me. Could we also have @jbarchibald check this over?

**Review by remear — CHANGES_REQUESTED** [review]
Overlooked one thing... the API spec needs to be updated with one targeting production.

**Comment by spencerroan** [comment]
@remear done

**Review by jbarchibald — APPROVED** [review]
Looks good to me

**Review by remear — APPROVED** [review]

**Pull request merged**
