### PR TITLE
Update main nav to be mobile-friendly

### PR DESCRIPTION
**Pull request by MisterPhilip**
#### Purpose

 * Update the main nav to be mobile-friendly

#### Changes

 * Added mobile-specific nav menu (screens ≤ 768px wide)

#### Caveats

 * Currently the links to Extensions & API go directly to the top-level page. Ideally both of those links would be an accordion and show the relevant subsections. However, each of the subsections do not have an overview page (e.g. https://developer.adobelaunch.com/extensions/reference/), thus nowhere to link to. Adding an overview page for most of the subsections should easy, but guidance on how Adobe would like to see the reference pages handled would be appreciated.
 

#### Additional helpful information

 * This is an alternative design to #58
 * It wasn't clear if there was a way to add an icon (hamburger menu) directly to the icons file, so I've inlined it
 * [Screenshots of the mobile nav](https://imgur.com/a/wDkym8u)

### CODE REVIEW

**Comment by thebenrob** [comment]
It'll probably be a couple weeks before we get a chance to review.
Is this one compatible/dependent on #58 in any way.  You think we should do one or the other? Or do both, but one should go first?

**Comment by MisterPhilip** [comment]
It'd be incompatible with #58 unfortunately; two different approaches to making it responsive (hide everything except the three main links in #58 vs. adding a separate full menu in this one)

**Review by thebenrob — APPROVED** [review]
I've checked this out locally and I like it.

**Comment by thebenrob** [comment]
@MisterPhilip Sorry it took so long.  Many thanks for making it usable on mobile devices!

**Pull request merged**
