### PR TITLE
Change `Developing...` headers to H2s

### PR DESCRIPTION
**Pull request by thatzacdavis**
#### Purpose
This makes scanning through the docs a bit easier visually.

#### Changes
This makes the `Developing...` headers H2s. This PR also makes the subheaders under them H3s. 

#### Caveats
I'm not sure why they were smaller headers before, and it may have been on purpose.

### CODE REVIEW

**Comment by remear** [comment]
These areas were intended to be sub-sections of the `Contributing` section. They could be brought up a level if others feel readability would increase. I'll leave this open for discussion for a bit in case others wish to share their opinion on this change.

**Comment by thebenrob** [comment]
I like having "Developing locally" and "Developing using a Docker container" being grouped together under a common heading.  If it's confusing having it grouped under the "Contributing" header, then perhaps we can make a new header that is just "Developing" and have them together under that heading.

**Comment by thatzacdavis** [comment]
What @thebenrob said makes sense to me. @remear would that work?

**Comment by remear** [comment]
Sure, let's move this forward with what @thebenrob outlined.

**Review by remear — APPROVED** [review]

**Pull request merged**
